exports_files(
    srcs = [
        "Cargo.toml",
    ],
)

# TODO: do not use me: openssl does not work.
# load("@cloud_hypervisor//:defs.bzl", "aliases", "all_crate_deps")
# load("@rules_rust//rust:defs.bzl", "rust_library")
#
# rust_library(
#     name = "test_infra",
#     srcs = glob(["src/**/*.rs"]),
#     aliases = aliases(),
#     proc_macro_deps = all_crate_deps(
#         proc_macro = True,
#     ),
#     visibility = ["//visibility:public"],  # Add this if not already present
#     deps = all_crate_deps(normal = True) + [
#     ],
# )
